version: '3'
services:
  app:
    image: bouchra445/express-sqlite-app
    container_name: express-sqlite-app
    volumes:
      - ./mydatabase.db:/usr/src/app/mydatabase.db
    ports:
      - "3002:3000"